Network:
  epochs: 50
  batch_size: 10
  n_steps: 50
  dataset: "XOR"
  rule: "BP"
  data_path: "./datasets/XOR"
  lr: 0.01
  loss: "average"
  tau_m: 5
  tau_s: 2
  model: "LIF"
  threshold: 1
  lr_dacay: 0.9
Layers:
  FC_1:
    layer_name: "FC_1"
    type: "linear"
    n_inputs: 2
    n_outputs: 64
  FC_2:
    layer_name: "FC_2"
    type: "linear"
    n_inputs: 64
    n_outputs: 128
  FC_3:
    layer_name: "FC_3"
    type: "linear"
    n_inputs: 128
    n_outputs: 256
  output:
    layer_name: "output"
    type: "FC"
    n_inputs: 256
    n_outputs: 1