Network:
  epochs: 50
  batch_size: 100
  n_steps: 2
  dataset: "XOR"
  rule: "ATBP"
  data_path: "./datasets/XOR"
  lr: 0.01
  loss: "average"
  tau_m: 5
  tau_s: 2
  model: "LIF"
  threshold: 1
  lr_dacay: 0.9
Layers:
  FC_1:
    layer_name: "FC_1"
    type: "linear"
    n_inputs: 2
    n_outputs: 800
  out:
    layer_name: "out"
    type: "FC"
    n_inputs: 800
    n_outputs: 1
